import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "../test-results/report.md");

/**
 * Vitest reporter → Markdown grouped by host / script folder.
 * Writes local report.md and appends to GITHUB_STEP_SUMMARY in Actions.
 */
export default class MarkdownReporter {
  onFinished(files = [], errors = []) {
    const groups = new Map(); // groupKey → rows[]
    let passed = 0;
    let failed = 0;
    let skipped = 0;

    for (const file of files) {
      collect(file.tasks || [], [], file.name || "", (path, t, fileName) => {
        const status = t.result?.state || "unknown";
        if (status === "pass") passed += 1;
        else if (status === "fail") failed += 1;
        else if (status === "skip" || status === "todo") skipped += 1;

        const { group, check } = classify(path, t.name || "", fileName);
        let note = "";
        if (status === "fail" && t.result?.errors?.length) {
          note = t.result.errors
            .map((e) => (e.message || String(e)).split("\n")[0])
            .join("; ")
            .replace(/\|/g, "/")
            .slice(0, 120);
        }
        if (!groups.has(group)) groups.set(group, []);
        groups.get(group).push({
          check: check.replace(/\|/g, "\\|"),
          status,
          icon: status === "pass" ? "✅" : status === "fail" ? "❌" : "⏭️",
          dur:
            t.result?.duration != null
              ? `${Math.round(t.result.duration)}ms`
              : "",
          note,
        });
      });
    }

    const total = passed + failed + skipped;
    const ok = failed === 0 && errors.length === 0;
    const lines = [
      `# ReDuckHunt report`,
      ``,
      ok ? `**Result: PASS**` : `**Result: FAIL**`,
      ``,
      `- Passed: **${passed}**`,
      `- Failed: **${failed}**`,
      `- Skipped: **${skipped}**`,
      `- Total: **${total}**`,
      `- Ran at: ${new Date().toISOString()}`,
      ``,
    ];

    const keys = [...groups.keys()].sort(sortGroups);
    for (const key of keys) {
      lines.push(`## \`${key}\``, ``);
      lines.push(`| Check | Status | Duration | Note |`);
      lines.push(`| --- | --- | --- | --- |`);
      for (const r of groups.get(key)) {
        lines.push(
          `| ${r.check} | ${r.icon} ${r.status} | ${r.dur} | ${r.note} |`,
        );
      }
      lines.push(``);
    }

    if (failed || errors.length) {
      lines.push(`## Failures`, ``);
      for (const key of keys) {
        for (const r of groups.get(key).filter((x) => x.status === "fail")) {
          lines.push(`### \`${key}\` — ${r.check}`, ``);
          if (r.note) lines.push(`- ${r.note}`, ``);
        }
      }
      for (const e of errors) {
        lines.push(`### Suite error`, ``, "```");
        lines.push(String(e?.stack || e?.message || e).slice(0, 2000));
        lines.push("```", ``);
      }
    }

    lines.push(`_Generated by ReDuckHunt MarkdownReporter._`, ``);

    const md = lines.join("\n");
    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, md);

    const summary = process.env.GITHUB_STEP_SUMMARY;
    if (summary) writeFileSync(summary, md, { flag: "a" });
  }
}

function collect(tasks, path, fileName, visit) {
  for (const t of tasks) {
    const next = [...path, t.name || ""];
    if (t.type === "test") visit(next, t, fileName);
    if (t.tasks?.length) collect(t.tasks, next, fileName, visit);
  }
}

/** Map describe/it path → { group: host/slug|host|framework, check } */
function classify(path, name, fileName) {
  // scripts > host > slug > check
  if (path[0] === "scripts" && path.length >= 4) {
    return { group: `${path[1]}/${path[2]}`, check: name || path[3] };
  }
  // cases > host > check
  if (path[0] === "cases" && path.length >= 3) {
    return { group: `${path[1]}/cases`, check: name || path[2] };
  }
  // checkExpect unit suite
  if (fileName.includes("checkExpect") || path[0] === "checkExpect") {
    return { group: "ReDuckHunt/checkExpect", check: name };
  }
  return {
    group: "ReDuckHunt",
    check: [...path.filter(Boolean), name].filter(Boolean).join(" › "),
  };
}

function sortGroups(a, b) {
  const rank = (k) => {
    if (k.startsWith("ReDuckHunt")) return 2;
    if (k.endsWith("/cases")) return 1;
    return 0;
  };
  const d = rank(a) - rank(b);
  return d !== 0 ? d : a.localeCompare(b);
}
