import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "../test-results/report.md");

/**
 * Vitest reporter → Markdown for local files and GitHub Actions job summaries.
 */
export default class MarkdownReporter {
  onFinished(files = [], errors = []) {
    const rows = [];
    let passed = 0;
    let failed = 0;
    let skipped = 0;

    for (const file of files) {
      for (const t of walk(file.tasks || [])) {
        const status = t.result?.state || "unknown";
        if (status === "pass") passed += 1;
        else if (status === "fail") failed += 1;
        else if (status === "skip" || status === "todo") skipped += 1;

        const dur =
          t.result?.duration != null ? `${Math.round(t.result.duration)}ms` : "";
        const icon =
          status === "pass" ? "✅" : status === "fail" ? "❌" : "⏭️";
        const name = (t.name || "").replace(/\|/g, "\\|");
        const fileName = (file.name || "").replace(/\|/g, "\\|");
        let note = "";
        if (status === "fail" && t.result?.errors?.length) {
          note = t.result.errors
            .map((e) => (e.message || String(e)).split("\n")[0])
            .join("; ")
            .replace(/\|/g, "/")
            .slice(0, 120);
        }
        rows.push({ icon, status, fileName, name, dur, note });
      }
    }

    const total = passed + failed + skipped;
    const ok = failed === 0 && errors.length === 0;
    const lines = [
      `# ReDuckHunt report`,
      ``,
      ok ? `**Result: PASS**` : `**Result: FAIL**`,
      ``,
      `- Passed: **${passed}**`,
      `- Failed: **${failed}**`,
      `- Skipped: **${skipped}**`,
      `- Total: **${total}**`,
      `- Ran at: ${new Date().toISOString()}`,
      ``,
      `## Cases`,
      ``,
      `| Status | File | Test | Duration | Note |`,
      `| --- | --- | --- | --- | --- |`,
    ];

    for (const r of rows) {
      lines.push(
        `| ${r.icon} ${r.status} | \`${r.fileName}\` | ${r.name} | ${r.dur} | ${r.note} |`,
      );
    }

    if (failed || errors.length) {
      lines.push(``, `## Failures`, ``);
      for (const r of rows.filter((x) => x.status === "fail")) {
        lines.push(`### ${r.name}`);
        lines.push(``);
        lines.push(`- File: \`${r.fileName}\``);
        if (r.note) lines.push(`- ${r.note}`);
        lines.push(``);
      }
      for (const e of errors) {
        lines.push(`### Suite error`);
        lines.push(``);
        lines.push("```");
        lines.push(String(e?.stack || e?.message || e).slice(0, 2000));
        lines.push("```");
        lines.push(``);
      }
    }

    lines.push(``, `_Generated by ReDuckHunt MarkdownReporter._`, ``);

    const md = lines.join("\n");
    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, md);

    // GitHub Actions job summary (visible on the run page — no download)
    const summary = process.env.GITHUB_STEP_SUMMARY;
    if (summary) {
      writeFileSync(summary, md, { flag: "a" });
    }
  }
}

function walk(tasks, acc = []) {
  for (const t of tasks) {
    if (t.type === "test") acc.push(t);
    if (t.tasks?.length) walk(t.tasks, acc);
  }
  return acc;
}
